# Generated by Django 4.1.3 on 2023-03-06 17:03

import dj_profiles.managers
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Электронная почта')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Отображаемое имя')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилие')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Изображение')),
                ('date_birth', models.DateField(verbose_name='Дата рождения')),
                ('is_staff', models.BooleanField(default=False, help_text='Определяет, может ли пользователь войти на сайт администратора.', verbose_name='Статус администратора')),
                ('is_active', models.BooleanField(default=False, help_text='Определяет, является ли пользователь действительным', verbose_name='Статус активации')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата присоединения')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', dj_profiles.managers.UserManager()),
            ],
        ),
    ]
