# Generated by Django 4.1.3 on 2023-03-06 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dj_articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dj_articles.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='article',
            name='reputation',
            field=models.ManyToManyField(blank=True, related_name='article_reputation', to=settings.AUTH_USER_MODEL, verbose_name='Репутация'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='dj_articles.tag', verbose_name='Теги'),
        ),
    ]
